export const OPEN_POST_MODAL = 'OPEN_POST_MODAL';
export const CLEAR_POST_MODAL = 'CLEAR_POST_MODAL';
export const CLOSE_POST_MODAL = 'CLOSE_POST_MODAL';
export const UPDATE_POST_MODAL = 'UPDATE_POST_MODAL';
