export const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL';
export const CLEAR_AUTH_MODAL = 'CLEAR_AUTH_MODAL';
export const CLOSE_AUTH_MODAL = 'CLOSE_AUTH_MODAL';
export const UPDATE_AUTH_MODAL = 'UPDATE_AUTH_MODAL';

export const CHANGE_VIEW_AUTH_MODAL = 'CHANGE_VIEW_AUTH_MODAL';
