export const INIT_CATEGORIES = 'INIT_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const REMOVE_CATEGORIES = 'REMOVE_CATEGORIES';
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';
